name: Art Image Bucket Dev Deployment

concurrency: art-image-dev-ev

# These actions happen whenever someone pushes or creates a pull request to the dev branch
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      
jobs:
  dev-deployment:
    runs-on: ubuntu-latest
    environment: art-image-dev-ev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    # npm ci is used instead of npm install for the following reasons:
    # 1. It provides a faster and cleaner installation by removing the existing node_modules folder.
    # 2. It ensures a consistent and reproducible dependency tree, as it installs the exact dependencies specified in package-lock.json.
    # 3. It enforces strict adherence between package.json and package-lock.json, ensuring that the dependencies are accurate and up-to-date.
    - name: Install dependencies and build
      run: npm ci

    # Connect to host using SSH key
    - name: Deploy to A2 Hosting
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}
        username: ${{ secrets.SFTP_USERNAME }}
        key: ${{ secrets.A2HOSTING_PRIVATE_KEY }}
        passphrase: ${{ secrets.A2HOSTING_PRIVATE_KEY_PASSPHRASE }}
        source: "./"
        target: ${{ secrets.SFTP_IMG_DESTINATION_PATH_DEV }}