name: Art Image Bucket Dev Deployment

concurrency: art-image-dev-ev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      
jobs:
  dev-deployment:
    runs-on: ubuntu-latest
    environment: art-image-dev-ev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies and build
      run: npm ci

    - name: Deploy to A2 Hosting
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}
        username: ${{ secrets.SFTP_USERNAME }}
        key: ${{ secrets.A2HOSTING_PRIVATE_KEY }}
        passphrase: ${{ secrets.A2HOSTING_PRIVATE_KEY_PASSPHRASE }}
        source: "./"
        target: ${{ secrets.SFTP_IMG_DESTINATION_PATH_DEV }}